### ISSUE TITLE
120 - get function not working properly to addEventListener 

### ISSUE THREAD

**Issue by arthur-debert** [arthur-debert/BulkLoader#119]
<pre>
<b>What steps will reproduce the problem?</b>

attempting to add an eventListener using the get method

bulkLoaderInstance.add(myurl,myid)
bulkLoaderInstance.get(myid).addEventListener(BulkLoaderProgress.COMPLETE,myfunction)

When executed a type coercion Error arises

<b>What is the expected output? What do you see instead?</b>
I get errors saying that there is a type coer cannot convert BulkProgressEvent to Event

<b>What version of the product are you using? On what operating system?</b>
most current downloaded today fresh copy and errors persist
OSX 10.6
Flex Builder 3 IDE

<b>Please provide any additional information below.</b>

</pre></br>Original link: http://code.google.com/p/bulk-loader/issues/detail?id=120

**Comment by arthur-debert** [comment]
debert - 2010-06-28 00:00:00 
None

**Comment by crirus** [comment]
Hello

I just added last version to my project and I keep getting that error mentioned above:

Type Coercion failed: cannot convert Function to br.com.stimuli.loading.loadingtypes.LoadingItem.
    at br.com.stimuli.loading::BulkLoader/_getNextItemToLoad()[D:\work\crilance\www\assets\dw_player\br\com\stimuli\loading\BulkLoader.as:789]

It appears that _items are sent or set as Function at some point....
I tried to debug but I can't understand why is htat happening, _items appears as an empty array and then populated with my items...
