### ISSUE TITLE
Type Coercion failed: cannot convert Function to br.com.stimuli.loading.loadingtypes.LoadingItem

### ISSUE THREAD

**Issue by ghost** [arthur-debert/BulkLoader#127]
This error appears in file BulkLoader on line 789:
Type Coercion failed: cannot convert Function to br.com.stimuli.loading.loadingtypes.LoadingItem

The surrounding code looks like this:

789: for each (var checkItem:LoadingItem in _items){
790: if (!checkItem._isLoading && checkItem.status != LoadingItem.STATUS_STOPPED && _canOpenConnectioForItem(checkItem)){
791: return checkItem;
792: }
793: }

In my own code, it happens during loader.start() function

Please help me to resolve it.

**Comment by arthur-debert** [comment]
Code works, pretty much (just look at the test suite). Please provide a simple test case where bulkloader fails and I'll reopen

**Comment by crirus** [comment]
Hello

It doens't work for me

Type Coercion failed: cannot convert Function to br.com.stimuli.loading.loadingtypes.LoadingItem.
    at br.com.stimuli.loading::BulkLoader/_getNextItemToLoad()[D:\work\crilance\www\assets\dw_player\br\com\stimuli\loading\BulkLoader.as:789]
